# Generated by Django 4.2.5 on 2023-09-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0002_login"),
    ]

    operations = [
        migrations.CreateModel(
            name="asik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Temparature", models.IntegerField()),
                ("HR_And_SPo2", models.TextField()),
                ("EGG", models.IntegerField()),
                ("Time", models.IntegerField()),
            ],
        ),
    ]
